let chromium;
try { ({chromium}=require('playwright')); } catch(error) { console.log('Browser check skipped: Playwright is not installed.'); process.exit(0); }
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{
const browser=await chromium.launch({headless:true,channel:'chrome'});for(const width of [360,390,1440]) {const page=await browser.newPage({viewport:{width,height:844},serviceWorkers:'block'});const errors=[];page.on('pageerror',e=>errors.push(e.message));let posts=0;const requestIds=[];
const settings={bookingDays:20,weeklySchedule:Array.from({length:7},(_,day)=>({day,slots:['10:00','14:00']}))};
await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname==='bagira.test'){let f=path.join(path.resolve(__dirname,'..'),u.pathname==='/'?'index.html':u.pathname);if(fs.existsSync(f)){const ext=path.extname(f);return route.fulfill({body:fs.readFileSync(f),contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.avif':'image/avif','.jpg':'image/jpeg','.json':'application/json'})[ext]||'application/octet-stream'});}return route.fulfill({status:404,body:''});}
if(u.hostname==='script.google.com'){if(route.request().method()==='POST'){posts++;requestIds.push(JSON.parse(route.request().postData()).requestId);if(width===360 && posts===1)return route.abort();return route.fulfill({json:{success:true,id:'test',telegramLink:'https://t.me/BagiraMasterBot?start=booking_'+'a'.repeat(32)}});}return route.fulfill({json:{success:true,days:[{date:'2026-09-30',available:false},{date:'2026-10-01',available:true}],today:'2026-09-30',currentTime:'08:00',scheduleSettings:settings,closedDays:[],bookings:u.searchParams.get('date')==='2026-09-30'?[{date:'2026-09-30',time:'10:00',status:'Активна'},{date:'2026-09-30',time:'14:00',status:'Активна'}]:[],slots:[{date:'2026-10-01',time:'10:00'}]}});}return route.abort();});
await page.goto('https://bagira.test/');await page.locator('#date').evaluate(el=>el.value='2026-09-30');await page.locator('#date').dispatchEvent('change');await page.locator('.nearest-slot-button').waitFor();assert.match(await page.locator('#dateWarning').innerText(),/свободных записей нет/);
await page.locator('#nextOpening').waitFor({state:'visible'});await page.locator('#service').selectOption('Педикюр');await page.locator('#nextOpeningBook').click();await page.waitForFunction(()=>document.querySelector('#selectedTime').value==='10:00');assert.equal(await page.locator('#date').inputValue(),'2026-10-01');assert.equal(await page.locator('#service').inputValue(),'Педикюр');await page.locator('#service').selectOption('');
await page.locator('.submit-button').click();await page.locator('#service[aria-invalid="true"]').waitFor();assert.equal(posts,0);await page.locator('#service').selectOption('Маникюр');await page.locator('#name').fill('Анна');await page.locator('#phone').fill('+375291234567');assert.equal(await page.locator('#telegram').count(),0);await page.reload();await page.waitForFunction(()=>document.querySelector('#selectedTime').value==='10:00');assert.equal(await page.locator('#name').inputValue(),'Анна');await page.locator('#bookingCalendar .calendar-grid button').first().waitFor();
await page.locator('.submit-button').click();await page.locator('#bookingReview').waitFor({state:'visible'});assert.equal(posts,0);await page.locator('#reviewEdit').click();await page.locator('#bookingReview').waitFor({state:'hidden'});assert.equal(await page.locator('#name').inputValue(),'Анна');
await page.locator('.submit-button').click();await page.locator('#bookingReview').waitFor({state:'visible'});if(width===390)await page.screenshot({path:'/tmp/bagira-review-mobile.png'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#reviewSend').click();if(width===360){await page.getByRole('button',{name:'Проверить отправку',exact:true}).waitFor();await page.reload();await page.getByRole('button',{name:'Проверить отправку',exact:true}).click();}await page.locator('#bookingSuccess').waitFor({state:'visible'});assert.equal(posts,width===360?2:1);if(width===360)assert.equal(requestIds[0],requestIds[1]);assert.match(await page.locator('#bookingDetails').innerText(),/по телефону/);assert.deepEqual(errors,[]);
await page.close();} await browser.close();console.log('Browser 360/390/1440: no slots, suggestion, selected slot, review/edit, one POST, Telegram connection, no overflow/errors passed.');
})().catch(e=>{console.error(e);process.exit(1)});
